In [4]:
print("Hello World");

Hello World


In [0]:
import numpy as np

#create an array
x = np.array([1,2,3])

In [0]:
a=np.zeros((2,2))
b=np.ones((2,2))

In [18]:
c = np.random.randint(10, size = (5))
d = np.random.randint(10, size = (5))

e = c/d
e

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([1.4       , 0.25      , 0.88888889,        inf,        inf])

In [19]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x,axis=0)) # Sum of col
print(np.sum(x,axis=1)) # Sum of row


10
[4 6]
[3 7]


In [0]:
# EXERCISE 

A = np.matrix('22 5 16 9;13 20 19 0;5 9 1 16;27 13 15 19')
B = np.matrix('10 5 20 20; 5 21 22 27; 26 19 22 3; 27 8 18 7')
C = np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
D = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6]) 

dtype('int64')

In [24]:
A+B

matrix([[32, 10, 36, 29],
        [18, 41, 41, 27],
        [31, 28, 23, 19],
        [54, 21, 33, 26]])

In [26]:
A-B

matrix([[ 12,   0,  -4, -11],
        [  8,  -1,  -3, -27],
        [-21, -10, -21,  13],
        [  0,   5,  -3,  12]])

In [37]:
np.multiply(A,B)

matrix([[220,  25, 320, 180],
        [ 65, 420, 418,   0],
        [130, 171,  22,  48],
        [729, 104, 270, 133]])

In [36]:
A*B

matrix([[ 904,  591, 1064,  686],
        [ 724,  846, 1118,  857],
        [ 553,  361,  608,  458],
        [1238,  845, 1498, 1069]])

In [38]:
C + D

array([27, 18, 41, 29, 30, 26, 25, 31, 30, 21, 23, 12, 25, 50, 28, 26])

In [39]:
C - D

array([ 21, -12,  -7, -15,  -8, -22,  17, -27,  18,  15, -17,  10,   3,
         0, -24,  14])

In [40]:
C * D

array([ 72,  45, 408, 154, 209,  48,  84,  58, 144,  54,  60,  11, 154,
       625,  52, 120])

In [41]:
np.matmul(C,D)

2298

In [42]:
A + 10

matrix([[32, 15, 26, 19],
        [23, 30, 29, 10],
        [15, 19, 11, 26],
        [37, 23, 25, 29]])

In [43]:
B + 10

matrix([[20, 15, 30, 30],
        [15, 31, 32, 37],
        [36, 29, 32, 13],
        [37, 18, 28, 17]])

In [44]:
c + 15

array([22, 16, 23, 17, 20])

In [45]:
d + 15

array([20, 19, 24, 15, 15])

In [46]:
print((2*A) + (2*B))

[[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [47]:
(A+B)*3


matrix([[ 96,  30, 108,  87],
        [ 54, 123, 123,  81],
        [ 93,  84,  69,  57],
        [162,  63,  99,  78]])

In [48]:
(A-B+A-B+B)*4 

matrix([[ 136,   20,   48,   -8],
        [  84,   76,   64, -108],
        [ -64,   -4,  -80,  116],
        [ 108,   72,   48,  124]])